
all: jetgpio_example.c trigger_test networked_trigger
	gcc -Wall -o jetgpio_example jetgpio_example.c -ljetgpio


trigger_test: trigger_test.c
	gcc -Wall -o trigger_test trigger_test.c -ljetgpio

networked_trigger: networked_trigger.c
	gcc -Wall -o networked_trigger networked_trigger.c -ljetgpio



