import sys

import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn.functional as F
from r2k import RollingKMeans, rolling_kmeans_cluster

# Radar parameters
FAST_TIME = 512
SLOW_TIME = 64
CARRIER_FREQ = 77e9
SPEED_OF_LIGHT = 3e8
LAMBDA = SPEED_OF_LIGHT / CARRIER_FREQ
CHIRP_DURATION = 100e-6
MAX_VELOCITY = LAMBDA / (4.0 * CHIRP_DURATION)
VELOCITY_RES = 2.0 * MAX_VELOCITY / SLOW_TIME
RANGE_MULTIPLIER = 9.0 / 256.0
MAX_RANGE = 9.0

rdm_path = "/Users/andrey/Downloads/frame_data/Node_Frame5_rdm.bin"


def load_rdm_binary(filepath):
    """Load binary RDM data file generated by C++.

    File format:
    - 2 integers: [SLOW_TIME, FAST_TIME] (dimensions)
    - SLOW_TIME * FAST_TIME floats: RDM data (already fftshifted)

    Args:
        filepath: Path to the .bin file

    Returns:
        2D numpy array of shape (SLOW_TIME, FAST_TIME)
    """
    with open(filepath, "rb") as f:
        # Read dimensions
        dims = np.fromfile(f, dtype=np.int32, count=2)
        slow_time, fast_time = dims[0], dims[1]

        # Read RDM data
        rdm_data = np.fromfile(f, dtype=np.float32, count=slow_time * fast_time)
        rdm_data = rdm_data.reshape((slow_time, fast_time))

    return rdm_data


# def cfar(rdm_data, guard_cells=2, training_cells=4, threshold_factor=2.0):
#     """Run CFAR (Constant False Alarm Rate) algorithm on RDM data.

#     This function applies a CFAR detection algorithm without cell averaging.
#     It processes the range-Doppler map and outputs detections based on a
#     threshold computed from surrounding cells.

#     Args:
#         rdm_data: Input range-Doppler map of shape (SLOW_TIME, FAST_TIME)
#         guard_cells: Number of guard cells around the cell under test (default: 2)
#         training_cells: Number of training cells around guard cells (default: 8)
#         threshold_factor: Multiplicative factor for threshold (default: 3.0)

#     Returns:
#         detections: Binary detection map of shape (SLOW_TIME, FAST_TIME//2)
#                    where 1 indicates detection and 0 indicates no detection
#     """
#     # Step 1: Get dimensions of input data
#     slow_time, fast_time = rdm_data.shape

#     # Step 2: Extract only the positive range bins (first half of fast time)
#     rdm_half = rdm_data[:, : fast_time // 2]
#     output_shape = (slow_time, fast_time // 2)

#     # Step 3: Initialize output detection matrix with zeros
#     detections = np.zeros(output_shape, dtype=np.float32)

#     # Step 4: Define the window size for CFAR processing
#     window_size = guard_cells + training_cells

#     # Step 5: Iterate through each cell in the RDM (excluding edges)
#     for i in range(window_size, slow_time - window_size):
#         for j in range(window_size, fast_time // 2 - window_size):
#             # Step 6: Extract the cell under test (CUT)
#             cell_under_test = rdm_half[i, j]

#             # Step 7: Define training region (exclude guard cells and CUT)
#             # Get the full window around the CUT
#             row_start = i - window_size
#             row_end = i + window_size + 1
#             col_start = j - window_size
#             col_end = j + window_size + 1

#             # Step 8: Extract training cells (excluding guard region)
#             training_region = []
#             for row in range(row_start, row_end):
#                 for col in range(col_start, col_end):
#                     # Skip cells within guard region
#                     if abs(row - i) > guard_cells or abs(col - j) > guard_cells:
#                         training_region.append(rdm_half[row, col])

#             # Step 9: Compute threshold from training cells
#             # Use maximum value in training region multiplied by threshold factor
#             if len(training_region) > 0:
#                 noise_level = np.percentile(
#                     training_region, 75
#                 )  # change this for noise margin
#                 threshold = noise_level * threshold_factor
#             else:
#                 threshold = float("inf")

#             # Step 10: Apply threshold test - mark as detection if CUT exceeds threshold
#             if cell_under_test > threshold:
#                 detections[i, j] = 1.0

#     # Step 11: Return the binary detection matrix
#     return detections
#


def cfar(
    rdm_data,
    guard_cells_doppler=4,
    guard_cells_range=16,
    training_cells_doppler=6,
    training_cells_range=12,
    threshold_factor=2.5,
):
    """Run CFAR (Constant False Alarm Rate) algorithm on RDM data.

    This function applies a CFAR detection algorithm with separate window
    parameters for Doppler (slow time) and Range (fast time) dimensions.
    It processes the range-Doppler map and outputs detections based on a
    threshold computed from surrounding cells.

    Args:
        rdm_data: Input range-Doppler map of shape (SLOW_TIME, FAST_TIME)
        guard_cells_doppler: Number of guard cells in Doppler/slow-time dimension (default: 4)
        guard_cells_range: Number of guard cells in Range/fast-time dimension (default: 8)
        training_cells_doppler: Number of training cells in Doppler dimension (default: 6)
        training_cells_range: Number of training cells in Range dimension (default: 12)
        threshold_factor: Multiplicative factor for threshold (default: 3.0)

    Returns:
        detections: Binary detection map of shape (SLOW_TIME, FAST_TIME//2)
                   where 1 indicates detection and 0 indicates no detection
    """
    # Step 1: Get dimensions of input data
    slow_time, fast_time = rdm_data.shape

    # Step 2: Extract only the positive range bins (first half of fast time)
    rdm_half = rdm_data[:, : fast_time // 2]
    output_shape = (slow_time, fast_time // 2)

    # Step 3: Initialize output detection matrix with zeros
    detections = np.zeros(output_shape, dtype=np.float32)

    # Step 4: Define the window sizes for each dimension
    window_size_doppler = guard_cells_doppler + training_cells_doppler
    window_size_range = guard_cells_range + training_cells_range

    # Step 5: Iterate through each cell in the RDM (excluding edges)
    # Use different margins for each dimension based on window sizes
    for i in range(window_size_doppler, slow_time - window_size_doppler):
        for j in range(window_size_range, fast_time // 2 - window_size_range):
            # Step 6: Extract the cell under test (CUT)
            cell_under_test = rdm_half[i, j]

            # Step 7: Define training region bounds (rectangular window)
            # Doppler dimension (rows) uses doppler window size
            row_start = i - window_size_doppler
            row_end = i + window_size_doppler + 1
            # Range dimension (cols) uses range window size
            col_start = j - window_size_range
            col_end = j + window_size_range + 1

            # Step 8: Extract training cells (excluding guard region and CUT)
            training_region = []
            for row in range(row_start, row_end):
                for col in range(col_start, col_end):
                    # Calculate distance from CUT in each dimension
                    doppler_distance = abs(row - i)
                    range_distance = abs(col - j)

                    # Include only cells outside the guard region in both dimensions
                    if (
                        doppler_distance > guard_cells_doppler
                        or range_distance > guard_cells_range
                    ):
                        training_region.append(rdm_half[row, col])

            # Step 9: Compute threshold from training cells
            # Use mean of training region for noise level estimation
            if len(training_region) > 0:
                noise_level = np.percentile(training_region, 75)
                threshold = noise_level * threshold_factor
            else:
                threshold = float("inf")

            # Step 10: Apply threshold test - mark as detection if CUT exceeds threshold
            if cell_under_test > threshold:
                detections[i, j] = 1.0

    # Step 11: Return the binary detection matrix
    return detections


def cfar_pytorch(
    rdm_data,
    guard_cells_doppler=4,
    guard_cells_range=8,
    training_cells_doppler=6,
    training_cells_range=12,
    threshold_factor=3.0,
    pad_value=None,
    pad_doppler=None,
    pad_range=None,
    device="cpu",
):
    """Run CFAR algorithm using PyTorch for GPU acceleration.

    This function applies a CFAR detection algorithm with separate window
    parameters for Doppler (slow time) and Range (fast time) dimensions.
    Uses PyTorch's unfold operation to extract all windows simultaneously
    and process them in parallel on GPU.

    Args:
        rdm_data: Input range-Doppler map of shape (SLOW_TIME, FAST_TIME)
        guard_cells_doppler: Number of guard cells in Doppler/slow-time dimension (default: 4)
        guard_cells_range: Number of guard cells in Range/fast-time dimension (default: 8)
        training_cells_doppler: Number of training cells in Doppler dimension (default: 6)
        training_cells_range: Number of training cells in Range dimension (default: 12)
        threshold_factor: Multiplicative factor for threshold (default: 3.0)
        pad_value: Value to use for padding. If None, uses mean of RDM data (default: None)
        pad_doppler: Number of cells to pad in Doppler dimension (top/bottom).
                     If None, uses window_size_doppler (default: None)
        pad_range: Number of cells to pad in Range dimension (left/right).
                   If None, uses window_size_range (default: None)
        device: Device to run on, 'cuda' or 'cpu' (default: 'cuda')

    Returns:
        detections: Binary detection map of shape (SLOW_TIME, FAST_TIME//2)
                   where 1 indicates detection and 0 indicates no detection
    """
    # Step 1: Get dimensions of input data
    slow_time, fast_time = rdm_data.shape

    # Step 2: Extract only the positive range bins (first half of fast time)
    rdm_half = rdm_data[:, : fast_time // 2]
    output_shape = (slow_time, fast_time // 2)

    # Step 3: Calculate window sizes for each dimension
    window_size_doppler = guard_cells_doppler + training_cells_doppler
    window_size_range = guard_cells_range + training_cells_range

    # Step 4: Determine padding sizes (use window sizes if not provided)
    if pad_doppler is None:
        pad_doppler = window_size_doppler
    if pad_range is None:
        pad_range = window_size_range

    # Step 4a: Validate parameters for dimensional consistency
    # Check that padding is sufficient for the window sizes
    if pad_doppler < window_size_doppler:
        raise ValueError(
            f"pad_doppler ({pad_doppler}) must be >= window_size_doppler ({window_size_doppler}). "
            f"Need at least {window_size_doppler} padding for guard_cells ({guard_cells_doppler}) + training_cells ({training_cells_doppler})."
        )
    if pad_range < window_size_range:
        raise ValueError(
            f"pad_range ({pad_range}) must be >= window_size_range ({window_size_range}). "
            f"Need at least {window_size_range} padding for guard_cells ({guard_cells_range}) + training_cells ({training_cells_range})."
        )

    # Validate input dimensions
    if slow_time <= 0 or fast_time <= 0:
        raise ValueError(f"Invalid RDM dimensions: {rdm_data.shape}")

    if rdm_data.ndim != 2:
        raise ValueError(f"RDM data must be 2D, got shape: {rdm_data.shape}")

    # Check that we have enough data after padding for window extraction
    padded_h = slow_time + 2 * pad_doppler
    padded_w = (fast_time // 2) + 2 * pad_range
    required_h = slow_time + 2 * window_size_doppler
    required_w = (fast_time // 2) + 2 * window_size_range

    if padded_h < required_h:
        raise ValueError(
            f"Insufficient padding in Doppler dimension. Padded height: {padded_h}, Required: {required_h}"
        )
    if padded_w < required_w:
        raise ValueError(
            f"Insufficient padding in Range dimension. Padded width: {padded_w}, Required: {required_w}"
        )

    # Step 5: Determine padding value (use mean if not provided)
    if pad_value is None:
        pad_value = np.mean(rdm_half)

    # Step 6: Convert to PyTorch tensor and move to device
    # Add batch and channel dimensions: [1, 1, H, W]
    rdm_tensor = torch.from_numpy(rdm_half).float().unsqueeze(0).unsqueeze(0)
    rdm_tensor = rdm_tensor.to(device)

    # Step 7: Pad the tensor for edge handling
    # F.pad format: (left, right, top, bottom)
    padded_rdm = F.pad(
        rdm_tensor,
        (pad_range, pad_range, pad_doppler, pad_doppler),
        mode="constant",
        value=pad_value,
    )

    # Step 8: Define the full window size for unfolding
    window_h = 2 * window_size_doppler + 1
    window_w = 2 * window_size_range + 1

    # Step 9: Use unfold to extract all windows simultaneously centered on each cell
    # The original data is at indices [pad_doppler:pad_doppler+slow_time, pad_range:pad_range+(fast_time//2)]
    # We need windows centered on each of these cells
    # Start extracting from (pad_doppler - window_size_doppler) to get first window centered on first cell
    # unfold(dimension, size, step) with step=1
    # Output size = (input_size - window_size + 1)
    # We want output = slow_time, so input = slow_time + window_h - 1 = slow_time + 2*window_size_doppler

    # Extract region that will give us exactly slow_time x (fast_time//2) windows
    extract_start_h = pad_doppler - window_size_doppler
    extract_end_h = pad_doppler + slow_time + window_size_doppler
    extract_start_w = pad_range - window_size_range
    extract_end_w = pad_range + (fast_time // 2) + window_size_range

    # Validate extraction bounds
    if extract_start_h < 0 or extract_end_h > padded_rdm.shape[2]:
        raise RuntimeError(
            f"Doppler extraction out of bounds: [{extract_start_h}:{extract_end_h}] for padded size {padded_rdm.shape[2]}"
        )
    if extract_start_w < 0 or extract_end_w > padded_rdm.shape[3]:
        raise RuntimeError(
            f"Range extraction out of bounds: [{extract_start_w}:{extract_end_w}] for padded size {padded_rdm.shape[3]}"
        )

    windows = (
        padded_rdm[:, :, extract_start_h:extract_end_h, extract_start_w:extract_end_w]
        .unfold(2, window_h, 1)
        .unfold(3, window_w, 1)
    )
    # Shape: [1, 1, slow_time, fast_time//2, window_h, window_w]

    # Validate windows shape
    expected_shape = (1, 1, slow_time, fast_time // 2, window_h, window_w)
    if windows.shape != expected_shape:
        raise RuntimeError(
            f"Window extraction produced unexpected shape: {windows.shape}, expected: {expected_shape}"
        )

    # Step 10: Reshape windows for easier processing
    # Combine spatial dimensions and flatten window dimensions
    windows = windows.squeeze(0).squeeze(
        0
    )  # [slow_time, fast_time//2, window_h, window_w]

    # Step 11: Create guard cell mask to exclude guard region from training
    # Build a mask where True = training cell, False = guard cell or CUT
    guard_mask = torch.ones((window_h, window_w), dtype=torch.bool, device=device)

    # Calculate center position of the window
    center_i = window_size_doppler
    center_j = window_size_range

    # Step 12: Set guard region and CUT to False in mask
    for i in range(window_h):
        for j in range(window_w):
            doppler_distance = abs(i - center_i)
            range_distance = abs(j - center_j)

            # Exclude cells within guard region (using OR logic)
            if (
                doppler_distance <= guard_cells_doppler
                and range_distance <= guard_cells_range
            ):
                guard_mask[i, j] = False

    # Step 13: Apply mask to extract training cells and compute noise level
    # Expand mask to match windows shape
    mask_expanded = guard_mask.unsqueeze(0).unsqueeze(0)  # [1, 1, window_h, window_w]
    mask_expanded = mask_expanded.expand_as(
        windows
    )  # [slow_time, fast_time//2, window_h, window_w]

    # Step 14: Compute mean of training cells for each window
    # Use masked_select alternative: set guard cells to 0 and count valid cells
    training_windows = windows * mask_expanded.float()

    # Sum training cell values and count of training cells
    training_sum = training_windows.sum(dim=(-2, -1))  # [slow_time, fast_time//2]
    training_count = mask_expanded.float().sum(
        dim=(-2, -1)
    )  # [slow_time, fast_time//2]

    # Compute noise level (mean of training cells)
    noise_level = training_sum / (
        training_count + 1e-10
    )  # Add epsilon to avoid division by zero

    # Step 15: Compute threshold for each cell
    threshold = noise_level * threshold_factor

    # Step 16: Extract cells under test from original unpadded data
    cells_under_test = rdm_tensor[0, 0, :, :]  # [slow_time, fast_time//2]

    # Validate threshold and cells_under_test have matching shapes
    if cells_under_test.shape != threshold.shape:
        raise RuntimeError(
            f"Shape mismatch: cells_under_test {cells_under_test.shape} != threshold {threshold.shape}"
        )

    # Step 17: Apply threshold test - compare CUT to threshold
    detections_tensor = (cells_under_test > threshold).float()

    # Step 18: Convert back to NumPy array and return
    detections = detections_tensor.cpu().numpy()

    return detections


def compute_axes(rdm_shape):
    """Compute range and velocity axes for RDM.

    Args:
        rdm_shape: Tuple of (slow_time, fast_time)

    Returns:
        range_axis: Array of range values in meters
        velocity_axis: Array of velocity values in m/s
    """
    slow_time, fast_time = rdm_shape
    range_axis = np.arange(fast_time // 2) * RANGE_MULTIPLIER
    velocity_bins = np.arange(slow_time) - slow_time // 2
    velocity_axis = velocity_bins * VELOCITY_RES
    return range_axis, velocity_axis


def plot_rdm(rdm_data):
    """Plot RDM without metadata.

    Args:
        rdm_data: 2D numpy array of RDM data
    """
    fig = plt.figure(figsize=(12, 8))

    # RDM plot
    ax1 = fig.add_subplot(111)
    rdm_display = rdm_data[:, : FAST_TIME // 2].T
    range_axis, velocity_axis = compute_axes(rdm_data.shape)
    extent = [velocity_axis[0], velocity_axis[-1], 0, range_axis[-1]]

    im = ax1.imshow(
        rdm_display,
        aspect="auto",
        origin="lower",
        extent=extent,
        cmap="jet",
        interpolation="nearest",
    )
    plt.colorbar(im, ax=ax1, label="Magnitude (dB)")

    ax1.set_xlabel("Velocity (m/s)", fontsize=12)
    ax1.set_ylabel("Range (m)", fontsize=12)
    ax1.set_title("Range-Doppler Map", fontsize=14)
    ax1.grid(True, alpha=0.3, linestyle="--")
    ax1.axvline(x=0, color="white", linestyle="--", alpha=0.5)

    plt.tight_layout()
    plt.show()


def main():
    test = load_rdm_binary(rdm_path)
    res = cfar_pytorch(
        test,
        pad_value=np.mean(test[:, :256]),
        guard_cells_doppler=4,
        guard_cells_range=16,
        training_cells_doppler=6,
        training_cells_range=24,
        threshold_factor=2.9,
        pad_doppler=32,
        pad_range=128,
        device="mps",
    )
    # plot_rdm(res)
    result = rolling_kmeans_cluster(res, n_clusters=3)
    plot_rdm(result)
    print(result.shape)
    print(result.size)


if __name__ == "__main__":
    sys.exit(main())
