import sys

import matplotlib.pyplot as plt
import numpy as np

# Radar parameters
FAST_TIME = 512
SLOW_TIME = 64
CARRIER_FREQ = 77e9
SPEED_OF_LIGHT = 3e8
LAMBDA = SPEED_OF_LIGHT / CARRIER_FREQ
CHIRP_DURATION = 100e-6
MAX_VELOCITY = LAMBDA / (4.0 * CHIRP_DURATION)
VELOCITY_RES = 2.0 * MAX_VELOCITY / SLOW_TIME
RANGE_MULTIPLIER = 9.0 / 256.0
MAX_RANGE = 9.0

rdm_path = "/Users/andrey/Downloads/frame_data/Node_Frame5_rdm.bin"


def load_rdm_binary(filepath):
    """Load binary RDM data file generated by C++.

    File format:
    - 2 integers: [SLOW_TIME, FAST_TIME] (dimensions)
    - SLOW_TIME * FAST_TIME floats: RDM data (already fftshifted)

    Args:
        filepath: Path to the .bin file

    Returns:
        2D numpy array of shape (SLOW_TIME, FAST_TIME)
    """
    with open(filepath, "rb") as f:
        # Read dimensions
        dims = np.fromfile(f, dtype=np.int32, count=2)
        slow_time, fast_time = dims[0], dims[1]

        # Read RDM data
        rdm_data = np.fromfile(f, dtype=np.float32, count=slow_time * fast_time)
        rdm_data = rdm_data.reshape((slow_time, fast_time))

    return rdm_data


# def cfar(rdm_data, guard_cells=2, training_cells=4, threshold_factor=2.0):
#     """Run CFAR (Constant False Alarm Rate) algorithm on RDM data.

#     This function applies a CFAR detection algorithm without cell averaging.
#     It processes the range-Doppler map and outputs detections based on a
#     threshold computed from surrounding cells.

#     Args:
#         rdm_data: Input range-Doppler map of shape (SLOW_TIME, FAST_TIME)
#         guard_cells: Number of guard cells around the cell under test (default: 2)
#         training_cells: Number of training cells around guard cells (default: 8)
#         threshold_factor: Multiplicative factor for threshold (default: 3.0)

#     Returns:
#         detections: Binary detection map of shape (SLOW_TIME, FAST_TIME//2)
#                    where 1 indicates detection and 0 indicates no detection
#     """
#     # Step 1: Get dimensions of input data
#     slow_time, fast_time = rdm_data.shape

#     # Step 2: Extract only the positive range bins (first half of fast time)
#     rdm_half = rdm_data[:, : fast_time // 2]
#     output_shape = (slow_time, fast_time // 2)

#     # Step 3: Initialize output detection matrix with zeros
#     detections = np.zeros(output_shape, dtype=np.float32)

#     # Step 4: Define the window size for CFAR processing
#     window_size = guard_cells + training_cells

#     # Step 5: Iterate through each cell in the RDM (excluding edges)
#     for i in range(window_size, slow_time - window_size):
#         for j in range(window_size, fast_time // 2 - window_size):
#             # Step 6: Extract the cell under test (CUT)
#             cell_under_test = rdm_half[i, j]

#             # Step 7: Define training region (exclude guard cells and CUT)
#             # Get the full window around the CUT
#             row_start = i - window_size
#             row_end = i + window_size + 1
#             col_start = j - window_size
#             col_end = j + window_size + 1

#             # Step 8: Extract training cells (excluding guard region)
#             training_region = []
#             for row in range(row_start, row_end):
#                 for col in range(col_start, col_end):
#                     # Skip cells within guard region
#                     if abs(row - i) > guard_cells or abs(col - j) > guard_cells:
#                         training_region.append(rdm_half[row, col])

#             # Step 9: Compute threshold from training cells
#             # Use maximum value in training region multiplied by threshold factor
#             if len(training_region) > 0:
#                 noise_level = np.percentile(
#                     training_region, 75
#                 )  # change this for noise margin
#                 threshold = noise_level * threshold_factor
#             else:
#                 threshold = float("inf")

#             # Step 10: Apply threshold test - mark as detection if CUT exceeds threshold
#             if cell_under_test > threshold:
#                 detections[i, j] = 1.0

#     # Step 11: Return the binary detection matrix
#     return detections
#


def cfar(
    rdm_data,
    guard_cells_doppler=4,
    guard_cells_range=16,
    training_cells_doppler=6,
    training_cells_range=24,
    threshold_factor=2.5,
):
    """Run CFAR (Constant False Alarm Rate) algorithm on RDM data.

    This function applies a CFAR detection algorithm with separate window
    parameters for Doppler (slow time) and Range (fast time) dimensions.
    It processes the range-Doppler map and outputs detections based on a
    threshold computed from surrounding cells.

    Args:
        rdm_data: Input range-Doppler map of shape (SLOW_TIME, FAST_TIME)
        guard_cells_doppler: Number of guard cells in Doppler/slow-time dimension (default: 4)
        guard_cells_range: Number of guard cells in Range/fast-time dimension (default: 8)
        training_cells_doppler: Number of training cells in Doppler dimension (default: 6)
        training_cells_range: Number of training cells in Range dimension (default: 12)
        threshold_factor: Multiplicative factor for threshold (default: 3.0)

    Returns:
        detections: Binary detection map of shape (SLOW_TIME, FAST_TIME//2)
                   where 1 indicates detection and 0 indicates no detection
    """
    # Step 1: Get dimensions of input data
    slow_time, fast_time = rdm_data.shape

    # Step 2: Extract only the positive range bins (first half of fast time)
    rdm_half = rdm_data[:, : fast_time // 2]
    output_shape = (slow_time, fast_time // 2)

    # Step 3: Initialize output detection matrix with zeros
    detections = np.zeros(output_shape, dtype=np.float32)

    # Step 4: Define the window sizes for each dimension
    window_size_doppler = guard_cells_doppler + training_cells_doppler
    window_size_range = guard_cells_range + training_cells_range

    # Step 5: Iterate through each cell in the RDM (excluding edges)
    # Use different margins for each dimension based on window sizes
    for i in range(window_size_doppler, slow_time - window_size_doppler):
        for j in range(window_size_range, fast_time // 2 - window_size_range):
            # Step 6: Extract the cell under test (CUT)
            cell_under_test = rdm_half[i, j]

            # Step 7: Define training region bounds (rectangular window)
            # Doppler dimension (rows) uses doppler window size
            row_start = i - window_size_doppler
            row_end = i + window_size_doppler + 1
            # Range dimension (cols) uses range window size
            col_start = j - window_size_range
            col_end = j + window_size_range + 1

            # Step 8: Extract training cells (excluding guard region and CUT)
            training_region = []
            for row in range(row_start, row_end):
                for col in range(col_start, col_end):
                    # Calculate distance from CUT in each dimension
                    doppler_distance = abs(row - i)
                    range_distance = abs(col - j)

                    # Include only cells outside the guard region in both dimensions
                    if (
                        doppler_distance > guard_cells_doppler
                        or range_distance > guard_cells_range
                    ):
                        training_region.append(rdm_half[row, col])

            # Step 9: Compute threshold from training cells
            # Use mean of training region for noise level estimation
            if len(training_region) > 0:
                noise_level = np.percentile(training_region, 75)
                threshold = noise_level * threshold_factor
            else:
                threshold = float("inf")

            # Step 10: Apply threshold test - mark as detection if CUT exceeds threshold
            if cell_under_test > threshold:
                detections[i, j] = 1.0

    # Step 11: Return the binary detection matrix
    return detections


def cfar_cube(rdm_avg, prev_rdm_avg, slow=64, fast=512):
    """Compute element-wise difference between current and previous RDM matrices.

    Args:
        rdm_avg: Current range-Doppler map average
        prev_rdm_avg: Previous range-Doppler map average
        slow: Number of slow time samples (default: 64)
        fast: Number of fast time samples (default: 512)

    Returns:
        cfar_cube: Element-wise difference array
    """
    cfar_cube = rdm_avg - prev_rdm_avg
    return cfar_cube


def compute_axes(rdm_shape):
    """Compute range and velocity axes for RDM.

    Args:
        rdm_shape: Tuple of (slow_time, fast_time)

    Returns:
        range_axis: Array of range values in meters
        velocity_axis: Array of velocity values in m/s
    """
    slow_time, fast_time = rdm_shape
    range_axis = np.arange(fast_time // 2) * RANGE_MULTIPLIER
    velocity_bins = np.arange(slow_time) - slow_time // 2
    velocity_axis = velocity_bins * VELOCITY_RES
    return range_axis, velocity_axis


def plot_rdm(rdm_data):
    """Plot RDM without metadata.

    Args:
        rdm_data: 2D numpy array of RDM data
    """
    fig = plt.figure(figsize=(12, 8))

    # RDM plot
    ax1 = fig.add_subplot(111)
    rdm_display = rdm_data[:, : FAST_TIME // 2].T
    range_axis, velocity_axis = compute_axes(rdm_data.shape)
    extent = [velocity_axis[0], velocity_axis[-1], 0, range_axis[-1]]

    im = ax1.imshow(
        rdm_display,
        aspect="auto",
        origin="lower",
        extent=extent,
        cmap="jet",
        interpolation="nearest",
    )
    plt.colorbar(im, ax=ax1, label="Magnitude (dB)")

    ax1.set_xlabel("Velocity (m/s)", fontsize=12)
    ax1.set_ylabel("Range (m)", fontsize=12)
    ax1.set_title("Range-Doppler Map", fontsize=14)
    ax1.grid(True, alpha=0.3, linestyle="--")
    ax1.axvline(x=0, color="white", linestyle="--", alpha=0.5)

    plt.tight_layout()
    plt.show()


def main():
    # rdm_avg = load_rdm_binary("rdm_avg.bin")
    # prev_rdm_avg = load_rdm_binary("prev_rdm_avg.bin")
    # cfar_cube = cfar_cube(rdm_avg, prev_rdm_avg)
    # print(cfar_cube)
    test = load_rdm_binary(rdm_path)
    # plot_rdm(test)
    print(cfar(test))
    plot_rdm(cfar(test))
    print(test.shape)
    print(test.size)


if __name__ == "__main__":
    sys.exit(main())
