#!/usr/bin/env python3
"""
Range-Doppler Map Plotting Script for Radar Data.
Called from implementation.cpp after data collection.

This script reads the binary RDM files and JSON metadata generated by the C++ radar
processing pipeline and creates visualizations of the range-doppler maps.

Usage:
    python3 rdm_plotter.py <data_directory>                    # Plot all frames
    python3 rdm_plotter.py <data_directory> --frame <num>      # Plot single frame
    python3 rdm_plotter.py <data_directory> --animation        # Create animation

Example:
    python3 rdm_plotter.py /home/fusionsense/Documents/Chirp/Node/test/non_thread/frame_data
"""

import argparse
import glob
import json
import os
import sys

import matplotlib
import numpy as np
import torch
import torch.nn.functional as F
from r2k import RollingKMeans

matplotlib.use("Agg")  # Non-interactive backend for headless systems (Jetson)
import matplotlib.animation as animation
import matplotlib.pyplot as plt
from matplotlib.colors import Normalize

# Radar parameters (must match implementation.cpp)
FAST_TIME = 512  # Number of range bins
SLOW_TIME = 64  # Number of doppler bins
CARRIER_FREQ = 77e9  # 77 GHz carrier frequency
SPEED_OF_LIGHT = 3e8
LAMBDA = SPEED_OF_LIGHT / CARRIER_FREQ  # ~0.0039m wavelength
CHIRP_DURATION = 100e-6  # 100 microseconds
MAX_VELOCITY = LAMBDA / (4.0 * CHIRP_DURATION)  # Maximum unambiguous velocity
VELOCITY_RES = 2.0 * MAX_VELOCITY / SLOW_TIME  # Velocity resolution per bin

# Range parameters (from implementation.cpp)
RANGE_MULTIPLIER = 9.0 / 256.0  # meters per bin (for half of FAST_TIME)
MAX_RANGE = 9.0  # Maximum range in meters


def load_rdm_binary(filepath):
    """Load binary RDM data file generated by C++.

    File format:
    - 2 integers: [SLOW_TIME, FAST_TIME] (dimensions)
    - SLOW_TIME * FAST_TIME floats: RDM data (already fftshifted)

    Args:
        filepath: Path to the .bin file

    Returns:
        2D numpy array of shape (SLOW_TIME, FAST_TIME)
    """
    with open(filepath, "rb") as f:
        # Read dimensions
        dims = np.fromfile(f, dtype=np.int32, count=2)
        slow_time, fast_time = dims[0], dims[1]

        # Read RDM data
        rdm_data = np.fromfile(f, dtype=np.float32, count=slow_time * fast_time)
        rdm_data = rdm_data.reshape((slow_time, fast_time))

    return rdm_data


def load_json_metadata(filepath):
    """Load JSON metadata for a frame.

    Args:
        filepath: Path to the .json file

    Returns:
        Dictionary with frame metadata
    """
    with open(filepath, "r") as f:
        return json.load(f)


def find_frame_files(data_dir, node_name=None):
    """Find all frame files in the data directory.

    Args:
        data_dir: Directory containing frame data
        node_name: Optional filter by node name

    Returns:
        List of tuples: (json_path, rdm_path, frame_num)
    """
    json_files = glob.glob(os.path.join(data_dir, "*_Frame*.json"))

    frames = []
    for json_path in json_files:
        # Extract frame number from filename
        basename = os.path.basename(json_path)
        try:
            parts = basename.replace(".json", "").split("_Frame")
            name = parts[0]
            frame_num = int(parts[1])
        except (IndexError, ValueError):
            continue

        # Check node name filter
        if node_name and name != node_name:
            continue

        # Check for corresponding RDM file
        rdm_path = json_path.replace(".json", "_rdm.bin")
        if os.path.exists(rdm_path):
            frames.append((json_path, rdm_path, frame_num))

    # Sort by frame number
    frames.sort(key=lambda x: x[2])
    return frames


def compute_axes(rdm_shape):
    """Compute range and velocity axes for plotting.

    Args:
        rdm_shape: Tuple of (slow_time, fast_time)

    Returns:
        range_axis: 1D array of range values in meters
        velocity_axis: 1D array of velocity values in m/s
    """
    slow_time, fast_time = rdm_shape

    # Range axis (only using first half due to fftshift behavior)
    # Range bins go from 0 to max_range
    range_axis = np.linspace(0, MAX_RANGE, fast_time // 2)

    # Velocity axis (centered at 0 after fftshift)
    # Bins are: [-max_vel, ..., 0, ..., +max_vel]
    velocity_axis = np.linspace(-MAX_VELOCITY, MAX_VELOCITY, slow_time)

    return range_axis, velocity_axis


def plot_rdm_single(rdm_data, metadata, output_path, show_detection=True):
    """Plot a single range-doppler map.

    Args:
        rdm_data: 2D numpy array of RDM data
        metadata: Dictionary with frame metadata
        output_path: Path to save the plot
        show_detection: Whether to highlight the detection point
    """
    fig, ax = plt.subplots(figsize=(12, 8))

    # Only show the relevant portion (first half of range)
    # Data is already fftshifted in doppler dimension
    rdm_display = rdm_data[:, : FAST_TIME // 2].T  # Transpose so range is Y-axis

    # Compute axes
    range_axis, velocity_axis = compute_axes(rdm_data.shape)

    # Create the heatmap
    extent = [velocity_axis[0], velocity_axis[-1], 0, range_axis[-1]]
    im = ax.imshow(
        rdm_display,
        aspect="auto",
        origin="lower",
        extent=extent,
        cmap="jet",
        interpolation="nearest",
    )

    # Add colorbar
    cbar = plt.colorbar(im, ax=ax, label="Magnitude (dB)")

    # Mark detection point if available
    if show_detection and "Range" in metadata and "Doppler" in metadata:
        detected_range = metadata["Range"]
        detected_doppler = metadata["Doppler"]
        ax.scatter(
            [detected_doppler],
            [detected_range],
            marker="x",
            s=200,
            c="white",
            linewidths=3,
            label=f"Detection: R={detected_range:.2f}m, V={detected_doppler:.2f}m/s",
        )
        ax.legend(loc="upper right", fontsize=10)

    # Labels and title
    ax.set_xlabel("Velocity (m/s)", fontsize=12)
    ax.set_ylabel("Range (m)", fontsize=12)

    node = metadata.get("Node", "Unknown")
    frame = metadata.get("Frame Number", 0)
    angle = metadata.get("Angle", 0)
    elapsed = metadata.get("Elapsed Time (ms)", 0)

    title = f"Range-Doppler Map - {node} Frame {frame}\n"
    title += f"Angle: {angle:.1f}°, Elapsed: {elapsed}ms"
    ax.set_title(title, fontsize=14)

    # Add grid
    ax.grid(True, alpha=0.3, linestyle="--")

    # Add zero-velocity line
    ax.axvline(x=0, color="white", linestyle="--", alpha=0.5, linewidth=1)

    plt.tight_layout()
    plt.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.close()

    print(f"Saved: {output_path}")


def plot_rdm_with_detection_info(rdm_data, metadata, output_path):
    """Plot RDM with additional detection information panel.

    Args:
        rdm_data: 2D numpy array of RDM data
        metadata: Dictionary with frame metadata
        output_path: Path to save the plot
    """
    fig = plt.figure(figsize=(16, 8))

    # Create gridspec for layout
    gs = fig.add_gridspec(1, 2, width_ratios=[3, 1])

    # RDM plot
    ax1 = fig.add_subplot(gs[0])
    rdm_display = rdm_data[:, : FAST_TIME // 2].T
    range_axis, velocity_axis = compute_axes(rdm_data.shape)
    extent = [velocity_axis[0], velocity_axis[-1], 0, range_axis[-1]]

    im = ax1.imshow(
        rdm_display,
        aspect="auto",
        origin="lower",
        extent=extent,
        cmap="jet",
        interpolation="nearest",
    )
    plt.colorbar(im, ax=ax1, label="Magnitude (dB)")

    # Mark detection
    if "Range" in metadata and "Doppler" in metadata:
        ax1.scatter(
            [metadata["Doppler"]],
            [metadata["Range"]],
            marker="o",
            s=300,
            facecolors="none",
            edgecolors="white",
            linewidths=3,
        )
        ax1.scatter(
            [metadata["Doppler"]],
            [metadata["Range"]],
            marker="+",
            s=200,
            c="white",
            linewidths=2,
        )

    ax1.set_xlabel("Velocity (m/s)", fontsize=12)
    ax1.set_ylabel("Range (m)", fontsize=12)
    ax1.set_title("Range-Doppler Map", fontsize=14)
    ax1.grid(True, alpha=0.3, linestyle="--")
    ax1.axvline(x=0, color="white", linestyle="--", alpha=0.5)

    # Detection info panel
    ax2 = fig.add_subplot(gs[1])
    ax2.axis("off")

    info_text = "Detection Information\n"
    info_text += "=" * 25 + "\n\n"
    info_text += f"Node: {metadata.get('Node', 'N/A')}\n"
    info_text += f"Frame: {metadata.get('Frame Number', 'N/A')}\n"
    info_text += f"Time: {metadata.get('Elapsed Time (ms)', 'N/A')} ms\n\n"
    info_text += "-" * 25 + "\n"
    info_text += "Target Parameters:\n"
    info_text += "-" * 25 + "\n\n"
    info_text += f"Range: {metadata.get('Range', 0):.3f} m\n"
    info_text += f"Angle: {metadata.get('Angle', 0):.1f}°\n"
    info_text += f"Doppler: {metadata.get('Doppler', 0):.3f} m/s\n"
    info_text += f"Doppler Bin: {metadata.get('Doppler Bin', 'N/A')}\n\n"

    # Compute XY position
    angle_rad = np.deg2rad(metadata.get("Angle", 0))
    range_m = metadata.get("Range", 0)
    x = range_m * np.sin(angle_rad)
    y = range_m * np.cos(angle_rad)

    info_text += "-" * 25 + "\n"
    info_text += "Cartesian Position:\n"
    info_text += "-" * 25 + "\n\n"
    info_text += f"X: {x:.3f} m\n"
    info_text += f"Y: {y:.3f} m\n"

    ax2.text(
        0.1,
        0.95,
        info_text,
        transform=ax2.transAxes,
        fontsize=11,
        verticalalignment="top",
        fontfamily="monospace",
        bbox=dict(boxstyle="round", facecolor="lightgray", alpha=0.8),
    )

    plt.tight_layout()
    plt.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.close()

    print(f"Saved: {output_path}")


def create_rdm_animation(frames_data, output_path, fps=5):
    """Create an animation of RDM frames.

    Args:
        frames_data: List of (rdm_data, metadata) tuples
        output_path: Path to save the animation (MP4 or GIF)
        fps: Frames per second
    """
    if not frames_data:
        print("No frames to animate")
        return

    fig, ax = plt.subplots(figsize=(12, 8))

    # Initialize with first frame
    rdm_data, metadata = frames_data[0]
    rdm_display = rdm_data[:, : FAST_TIME // 2].T
    range_axis, velocity_axis = compute_axes(rdm_data.shape)
    extent = [velocity_axis[0], velocity_axis[-1], 0, range_axis[-1]]

    im = ax.imshow(
        rdm_display,
        aspect="auto",
        origin="lower",
        extent=extent,
        cmap="jet",
        interpolation="nearest",
        animated=True,
    )
    plt.colorbar(im, ax=ax, label="Magnitude (dB)")

    (detection_marker,) = ax.plot([], [], "wx", markersize=15, mew=3)

    ax.set_xlabel("Velocity (m/s)", fontsize=12)
    ax.set_ylabel("Range (m)", fontsize=12)
    title = ax.set_title("", fontsize=14)
    ax.grid(True, alpha=0.3, linestyle="--")
    ax.axvline(x=0, color="white", linestyle="--", alpha=0.5)

    def update(frame_idx):
        rdm_data, metadata = frames_data[frame_idx]
        rdm_display = rdm_data[:, : FAST_TIME // 2].T
        im.set_array(rdm_display)

        # Update detection marker
        if "Range" in metadata and "Doppler" in metadata:
            detection_marker.set_data([metadata["Doppler"]], [metadata["Range"]])

        # Update title
        node = metadata.get("Node", "Unknown")
        frame = metadata.get("Frame Number", frame_idx)
        title.set_text(f"Range-Doppler Map - {node} Frame {frame}")

        return [im, detection_marker, title]

    anim = animation.FuncAnimation(
        fig, update, frames=len(frames_data), interval=1000 / fps, blit=True
    )

    # Save animation
    if output_path.endswith(".gif"):
        anim.save(output_path, writer="pillow", fps=fps)
    else:
        anim.save(output_path, writer="ffmpeg", fps=fps)

    plt.close()
    print(f"Saved animation: {output_path}")


def create_rdm_animation_cfar(frames_data, output_path, fps=5):
    """Create an animation of RDM frames.

    Args:
        frames_data: List of (rdm_data, metadata) tuples
        output_path: Path to save the animation (MP4 or GIF)
        fps: Frames per second
    """
    if not frames_data:
        print("No frames to animate")
        return

    fig, (ax1, ax2, ax3) = plt.subplots(
        3, 1, figsize=(12, 18), gridspec_kw={"height_ratios": [3, 2, 2]}
    )

    # Initialize with first frame
    rdm_data, cfar_data, km = (
        frames_data[0][0],
        frames_data[0][1] if len(frames_data[0]) > 1 else None,
        frames_data[0][2] if len(frames_data[0]) > 2 else None,
    )
    rdm_display = rdm_data[:, : FAST_TIME // 2].T
    range_axis, velocity_axis = compute_axes(rdm_data.shape)
    extent = [velocity_axis[0], velocity_axis[-1], 0, range_axis[-1]]

    im = ax1.imshow(
        rdm_display,
        aspect="auto",
        origin="lower",
        extent=extent,
        cmap="jet",
        interpolation="nearest",
        animated=True,
    )
    plt.colorbar(im, ax=ax1, label="Magnitude (dB)")

    (detection_marker,) = ax1.plot([], [], "wx", markersize=15, mew=3)

    ax1.set_xlabel("Velocity (m/s)", fontsize=12)
    ax1.set_ylabel("Range (m)", fontsize=12)
    title = ax1.set_title("", fontsize=14)
    ax1.grid(True, alpha=0.3, linestyle="--")
    ax1.axvline(x=0, color="white", linestyle="--", alpha=0.5)

    # Initialize CFAR subplot
    if cfar_data is not None:
        cfar_display = cfar_data[:, : FAST_TIME // 2].T
        im_cfar = ax2.imshow(
            cfar_display,
            aspect="auto",
            origin="lower",
            extent=extent,
            cmap="jet",
            interpolation="nearest",
            animated=True,
        )
        plt.colorbar(im_cfar, ax=ax2, label="CFAR Magnitude (dB)")
        (cfar_detection_marker,) = ax2.plot([], [], "wx", markersize=15, mew=3)
    else:
        im_cfar = None
        cfar_detection_marker = None

    ax2.set_xlabel("Velocity (m/s)", fontsize=12)
    ax2.set_ylabel("Range (m)", fontsize=12)
    cfar_title = ax2.set_title("CFAR Detection Map", fontsize=14)
    ax2.grid(True, alpha=0.3, linestyle="--")
    ax2.axvline(x=0, color="white", linestyle="--", alpha=0.5)

    # Initialize K-Means subplot
    if km is not None:
        km_display = km[:, : FAST_TIME // 2].T
        im_km = ax3.imshow(
            km_display,
            aspect="auto",
            origin="lower",
            extent=extent,
            cmap="jet",
            interpolation="nearest",
            animated=True,
        )
        plt.colorbar(im_km, ax=ax3, label="Cluster ID")
    else:
        im_km = None

    ax3.set_xlabel("Velocity (m/s)", fontsize=12)
    ax3.set_ylabel("Range (m)", fontsize=12)
    km_title = ax3.set_title("K-Means Clustering", fontsize=14)
    ax3.grid(True, alpha=0.3, linestyle="--")
    ax3.axvline(x=0, color="white", linestyle="--", alpha=0.5)

    plt.tight_layout()

    def update(frame_idx):
        frame_tuple = frames_data[frame_idx]
        rdm_data = frame_tuple[0]
        cfar_data = frame_tuple[1] if len(frame_tuple) > 1 else None
        km = frame_tuple[2] if len(frame_tuple) > 2 else None
        metadata = frame_tuple[-1]

        rdm_display = rdm_data[:, : FAST_TIME // 2].T
        im.set_array(rdm_display)

        # Update detection marker
        # if "Range" in metadata and "Doppler" in metadata:
        #     detection_marker.set_data([metadata["Doppler"]], [metadata["Range"]])

        # Update title
        # node = metadata.get("Node", "Unknown")
        # frame = metadata.get("Frame Number", frame_idx)
        title.set_text("Range-Doppler Map with CFAR")

        artists = [im, detection_marker, title]

        # Update CFAR plot
        if cfar_data is not None and im_cfar is not None:
            cfar_display = cfar_data[:, : FAST_TIME // 2].T
            im_cfar.set_array(cfar_display)
            if "Range" in metadata and "Doppler" in metadata:
                cfar_detection_marker.set_data(
                    [metadata["Doppler"]], [metadata["Range"]]
                )
            artists.extend([im_cfar, cfar_detection_marker, cfar_title])

        # Update K-Means plot
        if km is not None and im_km is not None:
            km_display = km[:, : FAST_TIME // 2].T
            im_km.set_array(km_display)
            artists.extend([im_km, km_title])

        return artists

    anim = animation.FuncAnimation(
        fig, update, frames=len(frames_data), interval=1000 / fps, blit=True
    )

    # Save animation
    if output_path.endswith(".gif"):
        anim.save(output_path, writer="pillow", fps=fps)
    else:
        anim.save(output_path, writer="ffmpeg", fps=fps)

    plt.close()
    print(f"Saved animation: {output_path}")


def process_all_frames(data_dir, output_dir):
    """Process all frames in the data directory.

    Args:
        data_dir: Directory containing frame data
        output_dir: Directory to save plots
    """
    frames = find_frame_files(data_dir)

    if not frames:
        print(f"No frame files found in {data_dir}")
        return

    print(f"Found {len(frames)} frames to process")

    for json_path, rdm_path, frame_num in frames:
        try:
            # Load data
            rdm_data = load_rdm_binary(rdm_path)
            metadata = load_json_metadata(json_path)

            # Generate output filename
            basename = os.path.basename(json_path).replace(".json", "")
            output_path = os.path.join(output_dir, f"{basename}_rdm.png")

            # Create plot
            plot_rdm_with_detection_info(rdm_data, metadata, output_path)

        except Exception as e:
            print(f"Error processing frame {frame_num}: {e}")
            continue


def process_single_frame(data_dir, output_dir, frame_num, node_name=None):
    """Process a single frame.

    Args:
        data_dir: Directory containing frame data
        output_dir: Directory to save plot
        frame_num: Frame number to process
        node_name: Optional node name filter
    """
    # Find the specific frame
    pattern = f"*_Frame{frame_num}.json"
    json_files = glob.glob(os.path.join(data_dir, pattern))

    if not json_files:
        print(f"Frame {frame_num} not found")
        return

    json_path = json_files[0]
    rdm_path = json_path.replace(".json", "_rdm.bin")

    if not os.path.exists(rdm_path):
        print(f"RDM binary file not found for frame {frame_num}")
        return

    # Load and plot
    rdm_data = load_rdm_binary(rdm_path)
    metadata = load_json_metadata(json_path)

    basename = os.path.basename(json_path).replace(".json", "")
    output_path = os.path.join(output_dir, f"{basename}_rdm.png")

    plot_rdm_with_detection_info(rdm_data, metadata, output_path)


def create_summary_plot(data_dir, output_dir):
    """Create a summary plot showing detections over time.

    Args:
        data_dir: Directory containing frame data
        output_dir: Directory to save plot
    """
    frames = find_frame_files(data_dir)

    if not frames:
        print("No frames found for summary")
        return

    # Collect data from all frames
    times = []
    ranges = []
    angles = []
    dopplers = []

    for json_path, rdm_path, frame_num in frames:
        try:
            metadata = load_json_metadata(json_path)
            times.append(metadata.get("Elapsed Time (ms)", 0))
            ranges.append(metadata.get("Range", 0))
            angles.append(metadata.get("Angle", 0))
            dopplers.append(metadata.get("Doppler", 0))
        except:
            continue

    if not times:
        print("No valid data for summary")
        return

    # Create summary plot
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))

    # Range over time
    ax1 = axes[0, 0]
    ax1.plot(times, ranges, "b.-")
    ax1.set_xlabel("Time (ms)")
    ax1.set_ylabel("Range (m)")
    ax1.set_title("Range vs Time")
    ax1.grid(True, alpha=0.3)

    # Angle over time
    ax2 = axes[0, 1]
    ax2.plot(times, angles, "g.-")
    ax2.set_xlabel("Time (ms)")
    ax2.set_ylabel("Angle (degrees)")
    ax2.set_title("Angle vs Time")
    ax2.grid(True, alpha=0.3)

    # Doppler over time
    ax3 = axes[1, 0]
    ax3.plot(times, dopplers, "r.-")
    ax3.set_xlabel("Time (ms)")
    ax3.set_ylabel("Doppler Velocity (m/s)")
    ax3.set_title("Doppler vs Time")
    ax3.axhline(y=0, color="k", linestyle="--", alpha=0.5)
    ax3.grid(True, alpha=0.3)

    # XY trajectory
    ax4 = axes[1, 1]
    x_coords = [r * np.sin(np.deg2rad(a)) for r, a in zip(ranges, angles)]
    y_coords = [r * np.cos(np.deg2rad(a)) for r, a in zip(ranges, angles)]

    scatter = ax4.scatter(x_coords, y_coords, c=times, cmap="viridis", s=50)
    ax4.plot(x_coords, y_coords, "k-", alpha=0.3)
    ax4.scatter([0], [0], marker="^", s=200, c="red", label="Radar")
    plt.colorbar(scatter, ax=ax4, label="Time (ms)")
    ax4.set_xlabel("X (m)")
    ax4.set_ylabel("Y (m)")
    ax4.set_title("Target Trajectory (XY Plane)")
    ax4.set_aspect("equal")
    ax4.grid(True, alpha=0.3)
    ax4.legend()

    plt.suptitle(f"Detection Summary - {len(times)} Frames", fontsize=14)
    plt.tight_layout()

    output_path = os.path.join(output_dir, "detection_summary.png")
    plt.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.close()

    print(f"Saved summary: {output_path}")


def cfar_pytorch(
    rdm_data,
    guard_cells_doppler=4,
    guard_cells_range=8,
    training_cells_doppler=6,
    training_cells_range=12,
    threshold_factor=3.0,
    pad_value=None,
    pad_doppler=None,
    pad_range=None,
    device="cpu",
):
    """Run CFAR algorithm using PyTorch for GPU acceleration.

    This function applies a CFAR detection algorithm with separate window
    parameters for Doppler (slow time) and Range (fast time) dimensions.
    Uses PyTorch's unfold operation to extract all windows simultaneously
    and process them in parallel on GPU.

    Args:
        rdm_data: Input range-Doppler map of shape (SLOW_TIME, FAST_TIME)
        guard_cells_doppler: Number of guard cells in Doppler/slow-time dimension (default: 4)
        guard_cells_range: Number of guard cells in Range/fast-time dimension (default: 8)
        training_cells_doppler: Number of training cells in Doppler dimension (default: 6)
        training_cells_range: Number of training cells in Range dimension (default: 12)
        threshold_factor: Multiplicative factor for threshold (default: 3.0)
        pad_value: Value to use for padding. If None, uses mean of RDM data (default: None)
        pad_doppler: Number of cells to pad in Doppler dimension (top/bottom).
                     If None, uses window_size_doppler (default: None)
        pad_range: Number of cells to pad in Range dimension (left/right).
                   If None, uses window_size_range (default: None)
        device: Device to run on, 'cuda' or 'cpu' (default: 'cuda')

    Returns:
        detections: Binary detection map of shape (SLOW_TIME, FAST_TIME//2)
                   where 1 indicates detection and 0 indicates no detection
    """
    # Step 1: Get dimensions of input data
    slow_time, fast_time = rdm_data.shape

    # Step 2: Extract only the positive range bins (first half of fast time)
    rdm_half = rdm_data[:, : fast_time // 2]
    output_shape = (slow_time, fast_time // 2)

    # Step 3: Calculate window sizes for each dimension
    window_size_doppler = guard_cells_doppler + training_cells_doppler
    window_size_range = guard_cells_range + training_cells_range

    # Step 4: Determine padding sizes (use window sizes if not provided)
    if pad_doppler is None:
        pad_doppler = window_size_doppler
    if pad_range is None:
        pad_range = window_size_range

    # Step 4a: Validate parameters for dimensional consistency
    # Check that padding is sufficient for the window sizes
    if pad_doppler < window_size_doppler:
        raise ValueError(
            f"pad_doppler ({pad_doppler}) must be >= window_size_doppler ({window_size_doppler}). "
            f"Need at least {window_size_doppler} padding for guard_cells ({guard_cells_doppler}) + training_cells ({training_cells_doppler})."
        )
    if pad_range < window_size_range:
        raise ValueError(
            f"pad_range ({pad_range}) must be >= window_size_range ({window_size_range}). "
            f"Need at least {window_size_range} padding for guard_cells ({guard_cells_range}) + training_cells ({training_cells_range})."
        )

    # Validate input dimensions
    if slow_time <= 0 or fast_time <= 0:
        raise ValueError(f"Invalid RDM dimensions: {rdm_data.shape}")

    if rdm_data.ndim != 2:
        raise ValueError(f"RDM data must be 2D, got shape: {rdm_data.shape}")

    # Check that we have enough data after padding for window extraction
    padded_h = slow_time + 2 * pad_doppler
    padded_w = (fast_time // 2) + 2 * pad_range
    required_h = slow_time + 2 * window_size_doppler
    required_w = (fast_time // 2) + 2 * window_size_range

    if padded_h < required_h:
        raise ValueError(
            f"Insufficient padding in Doppler dimension. Padded height: {padded_h}, Required: {required_h}"
        )
    if padded_w < required_w:
        raise ValueError(
            f"Insufficient padding in Range dimension. Padded width: {padded_w}, Required: {required_w}"
        )

    # Step 5: Determine padding value (use mean if not provided)
    if pad_value is None:
        pad_value = np.mean(rdm_half)

    # Step 6: Convert to PyTorch tensor and move to device
    # Add batch and channel dimensions: [1, 1, H, W]
    rdm_tensor = torch.from_numpy(rdm_half).float().unsqueeze(0).unsqueeze(0)
    rdm_tensor = rdm_tensor.to(device)

    # Step 7: Pad the tensor for edge handling
    # F.pad format: (left, right, top, bottom)
    padded_rdm = F.pad(
        rdm_tensor,
        (pad_range, pad_range, pad_doppler, pad_doppler),
        mode="constant",
        value=pad_value,
    )

    # Step 8: Define the full window size for unfolding
    window_h = 2 * window_size_doppler + 1
    window_w = 2 * window_size_range + 1

    # Step 9: Use unfold to extract all windows simultaneously centered on each cell
    # The original data is at indices [pad_doppler:pad_doppler+slow_time, pad_range:pad_range+(fast_time//2)]
    # We need windows centered on each of these cells
    # Start extracting from (pad_doppler - window_size_doppler) to get first window centered on first cell
    # unfold(dimension, size, step) with step=1
    # Output size = (input_size - window_size + 1)
    # We want output = slow_time, so input = slow_time + window_h - 1 = slow_time + 2*window_size_doppler

    # Extract region that will give us exactly slow_time x (fast_time//2) windows
    extract_start_h = pad_doppler - window_size_doppler
    extract_end_h = pad_doppler + slow_time + window_size_doppler
    extract_start_w = pad_range - window_size_range
    extract_end_w = pad_range + (fast_time // 2) + window_size_range

    # Validate extraction bounds
    if extract_start_h < 0 or extract_end_h > padded_rdm.shape[2]:
        raise RuntimeError(
            f"Doppler extraction out of bounds: [{extract_start_h}:{extract_end_h}] for padded size {padded_rdm.shape[2]}"
        )
    if extract_start_w < 0 or extract_end_w > padded_rdm.shape[3]:
        raise RuntimeError(
            f"Range extraction out of bounds: [{extract_start_w}:{extract_end_w}] for padded size {padded_rdm.shape[3]}"
        )

    windows = (
        padded_rdm[:, :, extract_start_h:extract_end_h, extract_start_w:extract_end_w]
        .unfold(2, window_h, 1)
        .unfold(3, window_w, 1)
    )
    # Shape: [1, 1, slow_time, fast_time//2, window_h, window_w]

    # Validate windows shape
    expected_shape = (1, 1, slow_time, fast_time // 2, window_h, window_w)
    if windows.shape != expected_shape:
        raise RuntimeError(
            f"Window extraction produced unexpected shape: {windows.shape}, expected: {expected_shape}"
        )

    # Step 10: Reshape windows for easier processing
    # Combine spatial dimensions and flatten window dimensions
    windows = windows.squeeze(0).squeeze(
        0
    )  # [slow_time, fast_time//2, window_h, window_w]

    # Step 11: Create guard cell mask to exclude guard region from training
    # Build a mask where True = training cell, False = guard cell or CUT
    guard_mask = torch.ones((window_h, window_w), dtype=torch.bool, device=device)

    # Calculate center position of the window
    center_i = window_size_doppler
    center_j = window_size_range

    # Step 12: Set guard region and CUT to False in mask
    for i in range(window_h):
        for j in range(window_w):
            doppler_distance = abs(i - center_i)
            range_distance = abs(j - center_j)

            # Exclude cells within guard region (using OR logic)
            if (
                doppler_distance <= guard_cells_doppler
                and range_distance <= guard_cells_range
            ):
                guard_mask[i, j] = False

    # Step 13: Apply mask to extract training cells and compute noise level
    # Expand mask to match windows shape
    mask_expanded = guard_mask.unsqueeze(0).unsqueeze(0)  # [1, 1, window_h, window_w]
    mask_expanded = mask_expanded.expand_as(
        windows
    )  # [slow_time, fast_time//2, window_h, window_w]

    # Step 14: Compute mean of training cells for each window
    # Use masked_select alternative: set guard cells to 0 and count valid cells
    training_windows = windows * mask_expanded.float()

    # Sum training cell values and count of training cells
    training_sum = training_windows.sum(dim=(-2, -1))  # [slow_time, fast_time//2]
    training_count = mask_expanded.float().sum(
        dim=(-2, -1)
    )  # [slow_time, fast_time//2]

    # Compute noise level (mean of training cells)
    noise_level = training_sum / (
        training_count + 1e-10
    )  # Add epsilon to avoid division by zero

    # Step 15: Compute threshold for each cell
    threshold = noise_level * threshold_factor

    # Step 16: Extract cells under test from original unpadded data
    cells_under_test = rdm_tensor[0, 0, :, :]  # [slow_time, fast_time//2]

    # Validate threshold and cells_under_test have matching shapes
    if cells_under_test.shape != threshold.shape:
        raise RuntimeError(
            f"Shape mismatch: cells_under_test {cells_under_test.shape} != threshold {threshold.shape}"
        )

    # Step 17: Apply threshold test - compare CUT to threshold
    detections_tensor = (cells_under_test > threshold).float()

    # Step 18: Convert back to NumPy array and return
    detections = detections_tensor.cpu().numpy()

    return detections


def main():
    parser = argparse.ArgumentParser(
        description="Range-Doppler Map Plotting Script",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("data_dir", help="Directory containing frame data")
    parser.add_argument("--frame", type=int, help="Process single frame number")
    parser.add_argument("--animation", action="store_true", help="Create animation")
    parser.add_argument("--node", help="Filter by node name")
    parser.add_argument(
        "--summary", action="store_true", help="Create summary plot only"
    )
    parser.add_argument("--output", help="Custom output directory")
    parser.add_argument(
        "--cfar", action="store_true", help="Create animation with cfar"
    )

    args = parser.parse_args()

    if not os.path.exists(args.data_dir):
        print(f"Error: Directory not found: {args.data_dir}")
        sys.exit(1)

    # Create output directory
    output_dir = args.output or os.path.join(args.data_dir, "rdm_plots")
    os.makedirs(output_dir, exist_ok=True)

    print("=" * 60)
    print("RANGE-DOPPLER MAP PLOTTING")
    print("=" * 60)
    print(f"Data directory: {args.data_dir}")
    print(f"Output directory: {output_dir}")
    print()

    if args.summary:
        # Only create summary
        create_summary_plot(args.data_dir, output_dir)
    elif args.frame is not None:
        # Process single frame
        print(f"Processing frame {args.frame}...")
        process_single_frame(args.data_dir, output_dir, args.frame, args.node)
    elif args.animation:
        # Create animation
        print("Creating animation...")
        frames = find_frame_files(args.data_dir, args.node)
        frames_data = []
        for json_path, rdm_path, _ in frames:
            try:
                rdm_data = load_rdm_binary(rdm_path)
                metadata = load_json_metadata(json_path)
                frames_data.append((rdm_data, metadata))
            except:
                continue

        if frames_data:
            output_path = os.path.join(output_dir, "rdm_animation.gif")
            create_rdm_animation(frames_data, output_path, fps=5)
    elif args.cfar:
        # Create animation with CFAR
        print("Creating animation with CFAR...")
        frames = find_frame_files(args.data_dir, args.node)
        frames_data = []
        i = 0
        km = RollingKMeans(n_clusters=3, window_size=5)
        for json_path, rdm_path, _ in frames:
            try:
                rdm_data = load_rdm_binary(rdm_path)
                cfar_data = cfar_pytorch(
                    rdm_data,
                    pad_value=np.mean(rdm_data[:, :256]),
                    guard_cells_doppler=4,
                    guard_cells_range=16,
                    training_cells_doppler=6,
                    training_cells_range=24,
                    threshold_factor=2.9,
                    pad_doppler=32,
                    pad_range=128,
                    device="mps",
                )
                res = km.fit_predict(cfar_data)
                i += 1
                print(f"Processed frame {i}/{len(frames)}")
                frames_data.append((rdm_data, cfar_data, res))

            except Exception as e:
                print(f"Error processing frame: {e}")
                continue

        if frames_data:
            output_path = os.path.join(output_dir, "rdm_animation_cfar.gif")
            create_rdm_animation_cfar(frames_data, output_path, fps=5)
    else:
        # Process all frames
        print("Processing all frames...")
        process_all_frames(args.data_dir, output_dir)

        # Also create summary
        print("\nCreating summary plot...")
        create_summary_plot(args.data_dir, output_dir)

    print("\n" + "=" * 60)
    print("PLOTTING COMPLETE")
    print("=" * 60)
    print(f"Output: {output_dir}/")

    return 0


if __name__ == "__main__":
    sys.exit(main())
