#!/usr/bin/env bash
# Build Fusion-Center/Laptop/.env from Fusion-Center/.env (or MQTT-Broker/.env) so laptop tools can load vars without manual exports.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
FC_ENV="${REPO_ROOT}/Fusion-Center/.env"
BROKER_ENV="${REPO_ROOT}/Fusion-Center/MQTT-Broker/.env"
LAPTOP_ENV="${REPO_ROOT}/Fusion-Center/Laptop/.env"

SRC_ENV=""
if [[ -f "${FC_ENV}" ]]; then
  SRC_ENV="${FC_ENV}"
elif [[ -f "${BROKER_ENV}" ]]; then
  SRC_ENV="${BROKER_ENV}"
else
  echo "Missing ${FC_ENV} and ${BROKER_ENV} — create Fusion-Center/.env on the Xavier and sync it here (or keep MQTT-Broker/.env)." >&2
  exit 1
fi

# shellcheck disable=SC1090
set -a
source "${SRC_ENV}"
set +a

umask 077
{
  echo "# Autogenerated by chirp_write_laptop_env.sh — do not commit (gitignored pattern may apply via parent .env rules)"
  echo "MQTT_HOST=${MQTT_HOST?}"
  echo "MQTT_PORT=${MQTT_PORT:-1883}"
  echo "MQTT_LAPTOP_USER=${MQTT_LAPTOP_USER?}"
  echo "MQTT_LAPTOP_PASS=${MQTT_LAPTOP_PASS?}"
  echo "DASHBOARD_PORT=${DASHBOARD_PORT:-5002}"
} >"${LAPTOP_ENV}"

chmod 600 "${LAPTOP_ENV}" 2>/dev/null || true
echo "Wrote ${LAPTOP_ENV}"
