#!/usr/bin/env bash
# Build Fusion-Center/Laptop/.env from MQTT-Broker/.env so laptop tools can load vars without manual exports.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
BROKER_ENV="${REPO_ROOT}/Fusion-Center/MQTT-Broker/.env"
LAPTOP_ENV="${REPO_ROOT}/Fusion-Center/Laptop/.env"

[[ -f "${BROKER_ENV}" ]] || { echo "Missing ${BROKER_ENV} — run chirp_runbook_xavier_mqtt.sh on Xavier first (or copy .env here)." >&2; exit 1; }

# shellcheck disable=SC1090
set -a
source "${BROKER_ENV}"
set +a

umask 077
{
  echo "# Autogenerated by chirp_write_laptop_env.sh — do not commit (gitignored pattern may apply via parent .env rules)"
  echo "MQTT_HOST=${MQTT_HOST?}"
  echo "MQTT_PORT=${MQTT_PORT:-1883}"
  echo "MQTT_LAPTOP_USER=${MQTT_LAPTOP_USER?}"
  echo "MQTT_LAPTOP_PASS=${MQTT_LAPTOP_PASS?}"
  echo "DASHBOARD_PORT=${DASHBOARD_PORT:-5002}"
} >"${LAPTOP_ENV}"

chmod 600 "${LAPTOP_ENV}" 2>/dev/null || true
echo "Wrote ${LAPTOP_ENV}"
